### mregd config ###

mregd_host		xrrp-ote.rrpproxy.net
mregd_port		2001

mregd_login
mregd_password

# Local socket for clients
#port        /tmp/mregd.service|unix
#port        localhost:6490|tcp
mregd_socket_username	command
mregd_socket_password	oir4wy2g

# The number of sessions to the server
#max_servers   2

# Send keep alive interval in seconds
#mregd_keepalive_interval 580

#pid_file    /var/run/mregd/mregd.pid

### logging
#log_level   3
#log_file		/var/log/mregd.log
#log_file       Sys::Syslog
#syslog_logsock unix
#syslog_ident   mregd
#syslog_logopt  pid|cons
#syslog_facility daemon
